name: careerbuilder
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_animations: ^1.1.3
  url_launcher: ^5.4.2
  smooth_star_rating: ^1.0.4+2
  curved_navigation_bar: ^0.3.2
  http: ^0.12.0+4
  shared_preferences: ^0.5.6+3
  rflutter_alert: ^1.0.3
  provider: ^4.0.5
  flutter_boom_menu: ^1.0.2
  percent_indicator: ^2.1.3
  image_picker: ^0.6.5
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.15.5+3
  firebase_database: ^3.1.3
  firebase_storage: ^3.1.5
  path:
  sqflite:
  intl: ^0.16.1
  font_awesome_flutter: ^8.8.1
  page_transition: ^1.1.4
  awesome_dialog:
  flutter_overboard: ^1.1.5
  flare_flutter: ^2.0.6
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/Tracks/desktop/images/Desktop.jpg
    - assets/Tracks/desktop/images/java.png
    - assets/Tracks/desktop/images/c sharp.png
    - assets/Tracks/desktop/images/c plus.png
    - assets/Tracks/desktop/images/python.png
    - assets/Tracks/desktop/images/c.png
    - assets/Tracks/desktop/images/profile.png
    - assets/Tracks/desktop/images/my.png
    - assets/Tracks/desktop/images/Desktop.jpg
    - assets/Tracks/desktop/images/java1.png
    - assets/Tracks/desktop/images/paython.png
    - assets/Tracks/desktop/images/mysql.png
    - assets/Tracks/desktop/images/c++.png
    - assets/Tracks/common/survey-tick.png
    - assets/Tracks/common/features.png
    - assets/Tracks/Web/computer-keyboard-laptop-screen-109371.png
    - assets/Tracks/Web/xml2.png
    - assets/Tracks/Web/web.jpeg
    - assets/Tracks/Web/angela.jpg
    - assets/Tracks/Web/flutter-max.jpg
    - assets/Tracks/Web/lamp2.jpg
    - assets/Tracks/Web/max.jpg
    - assets/Tracks/Web/freecodecamp.jpg
    - assets/Tracks/Web/boy.png
    - assets/Tracks/Web/girl.jpg
    - assets/Tracks/Web/zero1.jpg
    - assets/Tracks/Web/udemy.png
    - assets/Tracks/Web/css1.jpg
    - assets/Tracks/Web/bootstrap.jpg
    - assets/Tracks/Web/html.jpg
    - assets/Tracks/Web/javascript.jpg
    - assets/Tracks/Web/jquery.jpg
    - assets/Tracks/Web/mysql.jpg
    - assets/Tracks/Web/php.jpg
    - assets/Tracks/Web/xml.jpg
    - assets/Tracks/Web/ma.jpg
    - assets/Tracks/Web/left.png
    - assets/Tracks/Web/right.png
    - assets/Tracks/Web/bsleft.png
    - assets/Tracks/Web/cssright.png
    - assets/Tracks/Web/htmlleft.png
    - assets/Tracks/Web/jqleft.png
    - assets/Tracks/Web/jsright.png
    - assets/Tracks/Web/mysqlleft.png
    - assets/Tracks/Web/phpright.png
    - assets/Tracks/Web/xmlright.png
    - assets/Tracks/Web/bootsstrapcover.png
    - assets/Tracks/Web/csscover.png
    - assets/Tracks/Web/htmlcover.png
    - assets/Tracks/Web/jquerycover.png
    - assets/Tracks/Web/jscover.png
    - assets/Tracks/Web/mysqlcover.png
    - assets/Tracks/Web/phpcover.png
    - assets/Tracks/Web/xmlcover.png
    - assets/Tracks/common/survey-tick.png
    - assets/Tracks/common/features.png
    - assets/Tracks/mobile development/images/1024px-Circle-icons-profile.svg.PNG
    - assets/Tracks/mobile development/images/flutter.PNG
    - assets/Tracks/mobile development/images/flutterright.PNG
    - assets/Tracks/mobile development/images/freecodecamp.JPG
    - assets/Tracks/mobile development/images/jq.PNG
    - assets/Tracks/mobile development/images/jqueryright.PNG
    - assets/Tracks/mobile development/images/macbook-pro-2764678.JPG
    - assets/Tracks/mobile development/images/max.JPG
    - assets/Tracks/mobile development/images/my sql.PNG
    - assets/Tracks/mobile development/images/mysqlleft.PNG
    - assets/Tracks/mobile development/images/node.PNG
    - assets/Tracks/mobile development/images/nodejsleft.PNG
    - assets/Tracks/mobile development/images/react native left.PNG
    - assets/Tracks/mobile development/images/react.PNG
    - assets/Tracks/mobile development/images/ruby.PNG
    - assets/Tracks/mobile development/images/rubyright.PNG
    - assets/Tracks/mobile development/images/selective-focus-photography-of-person-holding-turned-on-1092644.JPG
    - assets/Tracks/mobile development/images/shahadat-rahman-gnyA8vd3Otc-unsplash.JPG
    - assets/Tracks/mobile development/images/udemy.PNG
    - assets/Tracks/mobile development/images/zero1.JPG
    - assets/Tracks/mobile development/common/Component 94 – 1.PNG
    - assets/Tracks/mobile development/common/survey-tick.PNG
    - assets/Tracks/Networking/download.jpeg
    - assets/Tracks/Networking/Component 98 – 1.png
    - assets/Tracks/Networking/Component 99 – 1.png
    - assets/Tracks/Networking/Component 97 – 1.png
    - assets/Tracks/Networking/Component 100 – 1.png
    - assets/Tracks/Networking/bash.png
    - assets/Tracks/Networking/obj-c.png
    - assets/Tracks/Networking/perl.png
    - assets/Tracks/Networking/ccna.png
    - assets/Tracks/Networking/1st instructor bash.jpg
    - assets/Tracks/Networking/2nd instractor bash.jpg
    - assets/Tracks/Networking/3rd instractor bash.jpg
    - assets/Tracks/Networking/4th istractor bash.jpg
    - assets/Tracks/Networking/5th istractor bash.jpg
    - assets/Tracks/Networking/1st instractor obj-c.jpg
    - assets/Tracks/Networking/2nd instrauctor obj-c.jpg
    - assets/Tracks/Networking/3rd instrauctor obj-c.jpg
    - assets/Tracks/Networking/4th instrauctor obj-c.jpg
    - assets/Tracks/Networking/5th instrauctor obj-c.jpg
    - assets/Tracks/Networking/1st instractor perl.jpg
    - assets/Tracks/Networking/2nd instractor perl.jpg
    - assets/Tracks/Networking/3rd instractor perl.jpg
    - assets/Tracks/Networking/4th instractor perl.jpg
    - assets/Tracks/Networking/5th instractor perl.jpg
    - assets/Tracks/Networking/1st instractor ccna.jpg
    - assets/Tracks/Networking/2nd instractor ccna.jpg
    - assets/Tracks/Networking/3rd instractor ccna.jpg
    - assets/Tracks/Networking/4th instractor ccna.jpg
    - assets/Tracks/Networking/5th instractor ccna.jpg
    - assets/Tracks/common/features.png
    - assets/Tracks/common/survey-tick.png
    - assets/Tracks/Other/ComponentCloud.png
    - assets/Tracks/Other/ComponentBigdata.png
    - assets/Tracks/Other/ComponentDataMining.png
    - assets/Tracks/Other/ComponentDatastructure2.png
    - assets/Tracks/Other/ComponentMath.png
    - assets/Tracks/Other/bigdata2.png
    - assets/Tracks/Other/cloud2.png
    - assets/Tracks/Other/datamining2.png
    - assets/Tracks/Other/datastructure2.png
    - assets/Tracks/Other/math2.png
    - assets/Tracks/Other/7.jpg
    - assets/Tracks/Other/AdelNasim.jpg
    - assets/Tracks/Other/DataScienceDojo.png
    - assets/Tracks/Other/Education4u.jpg
    - assets/Tracks/Other/EduonixLearningSolutions.jpg
    - assets/Tracks/Other/edureka!.png
    - assets/Tracks/Other/FCIHOCW.jpg
    - assets/Tracks/Other/MohamedFawzy.png
    - assets/Tracks/Other/mokafehaseu.jpg
    - assets/Tracks/Other/mycodeschool.jpg
    - assets/Tracks/Other/nihadcherim.jpg
    - assets/Tracks/Other/RANJIRAJ.jpg
    - assets/Tracks/Other/SaifBashar.jpg
    - assets/Tracks/Other/SDET.jpg
    - assets/Tracks/Other/Simplilearn.jpg
    - assets/Tracks/Other/StudySmart.jpg
    - assets/Tracks/Other/TekSmartLearning.jpg
    - assets/Tracks/Other/TheNewBaghdad.png
    - assets/Tracks/Other/TOCourses.jpg
    - assets/Tracks/Other/VTCSoftwareTraining.jpg
    - assets/Tracks/Common/survey-tick.png
    - assets/Tracks/Common/features.png
    - assets/Tracks/home/
    - assets/Test_Result/congratulation-logo/
    - assets/Test_Result/
    - assets/gifts/
    - assets/profile/
    - assets/challenge_cv/
    - assets/images/
    - assets/logoanmi.flr
    - assets/gifts/BTNOfApplyTheCode.png
    - assets/gifts/header shape.png
    - assets/gifts/container shape.png
    - assets/gifts/background.png

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
